######################################################################
##
## Filename: fetcher.udo
## Created on: Mon Oct 15 12:00:19 Romance Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
