######################################################################
##
## Filename: MUX.udo
## Created on: Fri Oct 19 12:47:22 Romance Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
