######################################################################
##
## Filename: tb_fetcher.udo
## Created on: Mon Oct 15 10:52:47 Romance Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
