######################################################################
##
## Filename: tb_processor_control.udo
## Created on: Mon Oct 01 07:49:52 Romance Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
