######################################################################
##
## Filename: tb_processor.udo
## Created on: Tue Sep 25 10:38:21 Romance Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
