######################################################################
##
## Filename: tb_register_file.udo
## Created on: Thu Sep 27 12:15:04 Romance Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
