onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_processor/uut/clk
add wave -noupdate /tb_processor/uut/reset
add wave -noupdate /tb_processor/uut/processor_enable
add wave -noupdate /tb_processor/uut/imem_address
add wave -noupdate /tb_processor/uut/imem_data_in
add wave -noupdate /tb_processor/uut/dmem_data_in
add wave -noupdate /tb_processor/uut/dmem_address
add wave -noupdate /tb_processor/uut/dmem_address_wr
add wave -noupdate /tb_processor/uut/dmem_data_out
add wave -noupdate /tb_processor/uut/dmem_write_enable
add wave -noupdate /tb_processor/uut/reg_dst
add wave -noupdate /tb_processor/uut/branch
add wave -noupdate /tb_processor/uut/memto_reg
add wave -noupdate /tb_processor/uut/alu_op
add wave -noupdate /tb_processor/uut/alu_src
add wave -noupdate /tb_processor/uut/reg_write
add wave -noupdate /tb_processor/uut/pc_src
add wave -noupdate /tb_processor/uut/state
add wave -noupdate /tb_processor/uut/i_bus_15_0
add wave -noupdate /tb_processor/uut/i_bus_15_11
add wave -noupdate /tb_processor/uut/i_bus_20_16
add wave -noupdate /tb_processor/uut/i_bus_25_21
add wave -noupdate /tb_processor/uut/mux_alusrc_output
add wave -noupdate /tb_processor/uut/shifter_output
add wave -noupdate /tb_processor/uut/signext_output
add wave -noupdate /tb_processor/uut/mux_memtoreg_output
add wave -noupdate /tb_processor/uut/alucomp_result
add wave -noupdate /tb_processor/uut/alucomp_zero
add wave -noupdate /tb_processor/uut/mux_regdst_output
add wave -noupdate /tb_processor/uut/registers_readdata2
add wave -noupdate /tb_processor/uut/registers_readdata1
add wave -noupdate /tb_processor/uut/adder1_output
add wave -noupdate /tb_processor/uut/adder1_output_cp
add wave -noupdate /tb_processor/uut/adder2_output
add wave -noupdate /tb_processor/uut/pc_write
add wave -noupdate /tb_processor/uut/mux_pcsrc_output
add wave -noupdate /tb_processor/uut/pc_output
add wave -noupdate /tb_processor/uut/mux_alusrc/selector
add wave -noupdate /tb_processor/uut/mux_alusrc/bus_in1
add wave -noupdate /tb_processor/uut/mux_alusrc/bus_in2
add wave -noupdate /tb_processor/uut/mux_alusrc/bus_out
add wave -noupdate /tb_processor/uut/mux_regdst/selector
add wave -noupdate /tb_processor/uut/mux_regdst/bus_in1
add wave -noupdate /tb_processor/uut/mux_regdst/bus_in2
add wave -noupdate /tb_processor/uut/mux_regdst/bus_out
add wave -noupdate /tb_processor/uut/mux_memtoreg/selector
add wave -noupdate /tb_processor/uut/mux_memtoreg/bus_in1
add wave -noupdate /tb_processor/uut/mux_memtoreg/bus_in2
add wave -noupdate /tb_processor/uut/mux_memtoreg/bus_out
add wave -noupdate /tb_processor/uut/mux_pcsrc/selector
add wave -noupdate /tb_processor/uut/mux_pcsrc/bus_in1
add wave -noupdate /tb_processor/uut/mux_pcsrc/bus_in2
add wave -noupdate /tb_processor/uut/mux_pcsrc/bus_out
add wave -noupdate /tb_processor/uut/shifter/bus_in
add wave -noupdate /tb_processor/uut/shifter/bus_out
add wave -noupdate /tb_processor/uut/signext/bus_in
add wave -noupdate /tb_processor/uut/signext/bus_out
add wave -noupdate /tb_processor/uut/alucomp/x
add wave -noupdate /tb_processor/uut/alucomp/y
add wave -noupdate /tb_processor/uut/alucomp/alu_in
add wave -noupdate /tb_processor/uut/alucomp/r
add wave -noupdate /tb_processor/uut/alucomp/flags
add wave -noupdate /tb_processor/uut/alucomp/less_aux
add wave -noupdate /tb_processor/uut/alucomp/cout_aux
add wave -noupdate /tb_processor/uut/alucomp/r_aux
add wave -noupdate /tb_processor/uut/adder1/x
add wave -noupdate /tb_processor/uut/adder1/y
add wave -noupdate /tb_processor/uut/adder1/cin
add wave -noupdate /tb_processor/uut/adder1/cout
add wave -noupdate /tb_processor/uut/adder1/r
add wave -noupdate /tb_processor/uut/adder1/caux
add wave -noupdate /tb_processor/uut/adder2/x
add wave -noupdate /tb_processor/uut/adder2/y
add wave -noupdate /tb_processor/uut/adder2/cin
add wave -noupdate /tb_processor/uut/adder2/cout
add wave -noupdate /tb_processor/uut/adder2/r
add wave -noupdate /tb_processor/uut/adder2/caux
add wave -noupdate /tb_processor/uut/registers/clk
add wave -noupdate /tb_processor/uut/registers/reset
add wave -noupdate /tb_processor/uut/registers/rw
add wave -noupdate /tb_processor/uut/registers/rs_addr
add wave -noupdate /tb_processor/uut/registers/rt_addr
add wave -noupdate /tb_processor/uut/registers/rd_addr
add wave -noupdate /tb_processor/uut/registers/write_data
add wave -noupdate /tb_processor/uut/registers/rs
add wave -noupdate /tb_processor/uut/registers/rt
add wave -noupdate /tb_processor/uut/registers/regs
add wave -noupdate /tb_processor/uut/reg_pc/clk
add wave -noupdate /tb_processor/uut/reg_pc/reset
add wave -noupdate /tb_processor/uut/reg_pc/wr
add wave -noupdate /tb_processor/uut/reg_pc/bus_in
add wave -noupdate /tb_processor/uut/reg_pc/bus_out
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
configure wave -namecolwidth 266
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {1166 ps}
